kyverno:
  namespace: kyverno

kyverno-policies:
  podSecurityStandard: restricted

kube-prometheus-stack:
  namespaceOverride: monitoring
  grafana:
    namespaceOverride: monitoring
  kube-state-metrics:
    namespaceOverride: monitoring
  prometheus-node-exporter:
    namespaceOverride: monitoring

policy-reporter:
  image:
    tag: dev
    registry: docker.io
    repository: fjogeleit/policy-reporter

  kyvernoPlugin:
    enabled: true
    image:
      tag: 1.3.0
  monitoring:
    enabled: true
    grafana:
      namespace: monitoring
      dashboards:
        enabled: true
    serviceMonitor:
      labels:
        release: policy-reporter-demo
  ui:
    image:
      tag: 1.3.4
    enabled: true
    plugins:
      kyverno: true