kyverno:
  namespace: kyverno

kyverno-policies:
  podSecurityStandard: restricted

kube-prometheus-stack:
  namespaceOverride: monitoring
  grafana:
    namespaceOverride: monitoring
  kube-state-metrics:
    namespaceOverride: monitoring
  prometheus-node-exporter:
    namespaceOverride: monitoring

policy-reporter:
  kyvernoPlugin:
    enabled: true
    blockReports:
      enabled: true
  monitoring:
    enabled: true
    grafana:
      namespace: monitoring
      dashboards:
        enabled: true
    serviceMonitor:
      labels:
        release: policy-reporter-demo
  ui:
    enabled: true
    plugins:
      kyverno: true