apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-reporter
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: policy-reporter
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://kyverno.github.io/policy-reporter'
    chart: policy-reporter
    targetRevision: 2.8.0
    helm:
      releaseName: policy-reporter
      values: |
        kyvernoPlugin:
          enabled: true
        monitoring:
          enabled: true
          grafana:
            namespace: monitoring
            dashboards:
              enabled: true
        ui:
          enabled: true
          plugins:
            kyverno: true
